### PR TITLE
Updating the README for PR#24

### PR DESCRIPTION
**Pull request by roshan1337d**
### Why:

Updating the README for changes introduced by PR #24 

### What's being changed:

- Including steps to turn on the permission for actions to create and approve PRs in repository settings.
- Including steps to manually run the 1st workflow due to the change of #24 PR.
- Included screenshots for both steps.

### Check off the following:

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by Henry0071** [comment]
> ### Why:
> 
> 
> 
> Updating the README for changes introduced by PR #24 
> 
> 
> 
> ### What's being changed:
> 
> 
> 
> - Including steps to turn on the permission for actions to create and approve PRs in repository settings.
> 
> - Including steps to manually run the 1st workflow due to the change of #24 PR.
> 
> - Included screenshots for both steps.
> 
> 
> 
> ### Check off the following:
> 
> 
> 
> - [x] For workflow changes, I have verified the Actions workflows function as expected.
> 
> - [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).
> 
>

**Review by magic-taimania — APPROVED** [review]

**Comment by pcjoshiG** [comment]
Its looking fine

**Comment by Gaston-MaikMax** [comment]
esta chido

**Comment by TanjaTJ** [comment]
This is looking good

**Review by TanjaTJ — COMMENTED** [review]
but I can't assign myself as a reviewer

**Comment by VaishaliKotadiya** [comment]
This is looking good

**Comment by VaishaliKotadiya** [comment]
I can't assign myself as a reviewer

**Comment by nubiamstewart** [comment]
approved

**Comment by heiskr** [comment]
Hi @roshan1337d , thanks for investigating this. After discussing the situation with a few internal teams, the decision was to remove all usage of `gh pr create` and `gh pr review` from Skills courses. We're working on updating the course contents in https://github.com/skills/review-pull-requests/pull/29. I will close this pull request out, but feel free to open more pull requests :)

**Pull request closed without merging**
